projects:
  ekibackend:
    schemaPath: amplify/backend/api/ekibackend/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 5
extensions:
  amplify:
    version: 3
