export const locationAmplify = {
    "en": {
        "Sign In": "Sign In",
        "Sign Up": "Sign Up",
        "Sign in": "Log in",
        "Sign in to your account": "Welcome Back!",
        "Username": "Enter your username",
        "Password": "Enter your password",
        "Enter your Password": "Enter your password",
        "Forgot your password?": "Reset Password",
        "Create Account": "Register",
        "Create a new account": "New User",
        "Confirm Password": "Confirm your password",
        "Email": "Enter your email",
        "Phone Number": "Enter your phone number",
        "Reset your password": "Forgot your password?",
        "Enter your username": "Username or Email",
        "Send code": "Reset my password",
        "Back to Sign In": "Back to Login",
        "Loading": "QR code would show here",
        "Code": "2FA Code",
        "Confirm": "Confirm 2FA",
        "Back to Sign In": "Back to Login",
        "Family Name": "Lastname",
        "Nickname": "Nickname",
        "Given Name": "Name",
        "Phone": "Phone number",
        "Enter your Email": "Enter your email",
        "Reset Password": "Reset Password"
    },
    "es": {
        "Sign In": "Inicia sesión",
        "Sign Up": "Crear cuenta",
        "Sign in": "Inicia sesión",
        "Sign in to your account": "Bienvenido a Kokomi",
        "Username": "Ingresa tu correo electrónico",
        "Password": "Digita tu contraseña",
        "Enter your Password": "Digita tu contraseña",
        "Forgot your password?": "¿Olvidaste tu contraseña?",
        "Create Account": "Registrarse",
        "Create a new account": "Crear usuario",
        "Confirm Password": "Confirma tu contraseña",
        "Email": "Correo electrónico",
        "Phone Number": "Ingresa tu número de teléfono",
        "Reset your password": "¿Olvidaste tu contraseña?",
        "Enter your username": "Correo electrónico",
        "Send code": "Recuperar contraseña",
        "Back to Sign In": "¿Aún no tienes cuenta en Kokomi?",
        "Loading": "Un código QR se mostrara aquí",
        "Code": "2FA código",
        "Confirm": "Confirmar 2FA",
        "Back to Sign In": "¿Ya tienes cuenta? Ingresa",
        "Family Name": "¿Cuales son tus apellidos?",
        "Nickname": "¿Cómo prefieres que te llamemos? (Nickname)",
        "Given Name": "¿Cuál es tu nombre?",
        "Phone": "Número celular",
        "Enter your Email": "Ingresa tu correo electrónico",
        "Reset Password": "Recuperar contraseña"
    }
}